# 应用服务 WEB 访问端口
spring:
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        server- addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: maploj-backend-user-service
          uri: lb://maploj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: maploj-backend-question-service
          uri: lb://maploj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: maploj-backend-judge-service
          uri: lb://maploj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: maploj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2


